<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>zucchini</string>
	</array>
	<key>firstLineMatch</key>
	<string>Start on the(.*)</string>
	<key>foldingStartMarker</key>
	<string>^\s*(.*on the ".+" screen:)\s*</string>
	<key>foldingStopMarker</key>
	<string>^\n*$</string>
	<key>name</key>
	<string>Zucchini</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#screen_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tap_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings_single_quote</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings_double_quote</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(#.*)</string>
		</dict>
		<key>screen_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.zucchini.screen</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.zucchini.screen.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([^#]* on the (".+") screen:)\s*</string>
		</dict>
		<key>strings_double_quote</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<key>strings_single_quote</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;![a-zA-Z"])'</string>
			<key>end</key>
			<string>'(?![a-zA-Z])</string>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<key>tap_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.zucchini.feature.tap</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s(Tap |Confirm |\* )</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.zucchini.feature</string>
	<key>uuid</key>
	<string>F8270198-54D0-496B-8C62-98B0121B760A</string>
</dict>
</plist>
